apiVersion: batch/v1
kind: CronJob
metadata:
  name: minecraft-backup
spec:
  schedule: "0 2 * * *"  # Backup diário às 2:00
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: itzg/minecraft-server:latest  # Use a imagem que contém os scripts
            command: ["/bin/sh", "-c"]
            args:
            - |
              LOG_FILE="/backups/minecraft-backup-$(date +\%Y\%m\%d\%H\%M\%S).log"
              BACKUP_FILE="/backups/minecraft-backup-$(date +\%Y\%m\%d\%H\%M\%S).tar.gz"
              MOUNT_POINT="/mnt/backup"

              # Iniciar log
              echo "Iniciando processo de backup em $(date)" | tee -a $LOG_FILE

              # Montar o compartilhamento SMB
              echo "Montando o compartilhamento SMB..." | tee -a $LOG_FILE
              mount -t cifs //192.168.100.204/minecraft-backups /mnt/backup -o username=helinton,password=0l1v31r@,file_mode=0777,dir_mode=0777

              # Verificar se a montagem foi bem-sucedida
              if [ $? -eq 0 ]; then
                echo "Montagem do compartilhamento SMB bem-sucedida em $(date)" | tee -a $LOG_FILE

                # Executar o backup e registrar no log
                echo "Executando backup do diretório /data para $BACKUP_FILE" | tee -a $LOG_FILE
                tar czf $BACKUP_FILE /data 2>> $LOG_FILE

                if [ $? -eq 0 ]; then
                  echo "Backup concluído com sucesso em $(date)" | tee -a $LOG_FILE
                else
                  echo "Erro ao executar o backup em $(date)" | tee -a $LOG_FILE
                fi
              else
                echo "Falha ao montar o compartilhamento SMB em $(date)" | tee -a $LOG_FILE
              fi

              # Desmontar o compartilhamento SMB após o backup
              echo "Desmontando o compartilhamento SMB..." | tee -a $LOG_FILE
              umount /mnt/backup

              if [ $? -eq 0 ]; then
                echo "Desmontagem do SMB concluída com sucesso em $(date)" | tee -a $LOG_FILE
              else
                echo "Erro ao desmontar o SMB em $(date)" | tee -a $LOG_FILE
              fi
            volumeMounts:
            - name: minecraft-v2-data
              mountPath: /data
            - name: smb-backup-storage
              mountPath: /backups
          restartPolicy: OnFailure
          volumes:
          - name: minecraft-v2-data
            persistentVolumeClaim:
              claimName: minecraft-v2.1-pvc
          - name: smb-backup-storage
            persistentVolumeClaim:
              claimName: smb-backup-pvc
