apiVersion: batch/v1
kind: CronJob
metadata:
  name: minecraft-backup
spec:
  schedule: "0 2 * * *"  # Backup diário às 2:00
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: itzg/minecraft-server:latest  # Use a imagem que contém os scripts
            command: ["/bin/sh", "-c"]
            args:
            - |
              # Executar o backup
              echo "Executando backup..."
              tar czf /backups/minecraft-backup-$(date +\%Y\%m\%d\%H\%M\%S).tar.gz /data
            volumeMounts:
            - name: minecraft-v2-data
              mountPath: /data
            - name: smb-backup-storage
              mountPath: /backups
          restartPolicy: OnFailure
          volumes:
          - name: minecraft-v2-data
            persistentVolumeClaim:
              claimName: minecraft-v2-pvc
          - name: smb-backup-storage
            persistentVolumeClaim:
              claimName: smb-backup-pvc
