apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-v2
  labels:
    app: minecraft-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-v2
  template:
    metadata:
      labels:
        app: minecraft-v2
    spec:
      containers:
      - name: minecraft-v2
        image: itzg/minecraft-server:latest
        ports:
        - containerPort: 25565
        env:
        - name: EULA
          value: "TRUE" # Aceitar EULA
        - name: ONLINE_MODE
          value: "FALSE"
        - name: ENABLE_CHEATS
          value: "TRUE" # Habilitar cheats
        - name: MODE
          value: "survival"
        - name: DIFFICULTY
          value: "easy"
        - name: MEMORY
          value: "2G" # Memória RAM alocada
        resources:
          limits:
            memory: "4Gi"
            cpu: "2000m"
          requests:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: minecraft-v2-data
          mountPath: /data
      - name: backup-container
        image: ubuntu:latest
        command: ["/bin/sh", "-c"]
        args: ["while true; do sleep 3600; done"]  # Manter o contêiner ativo
        volumeMounts:
        - name: minecraft-v2-data
          mountPath: /data  # Mesma pasta de dados do Minecraft
        - name: backup-storage
          mountPath: /backups  # Pasta onde os backups serão salvos
      volumes:
      - name: minecraft-v2-data
        persistentVolumeClaim:
          claimName: minecraft-v2-pvc
      - name: backup-storage
        persistentVolumeClaim:
          claimName: backup-pvc
      - name: minecraft-v2-config
        configMap:
          name: minecraft-v2-config
