apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-backup-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: smb-backup
    volumeAttributes:
      source: "//192.168.100.204/minecraft-backups"
    nodeStageSecretRef:
      name: smb-credentials
      namespace: default
